added a function to find compile_commands.json in build dir
thibthib18/ros-nvim pull request #6
Opened 2022-05-21 11:05 UTC by DavidePatria

As discussed in another issue I tried to write a function that allows to automatically pass `compile_commands.json` path as an argmument to `clangd` through lspconfig as follows:

```
local ros = require('ros-nvim')

lspconfig.clangd.setup{
  on_attach = on_attach,
  capabilities = capabilities,

  filetypes = {"c", "cpp"},
  -- cmd = cmd,
  cmd = {"clangd",
    -- "--compile-commands-dir='build'",
    "--suggest-missing-includes",
    "--clang-tidy",
    "--header-insertion=iwyu",
    "--all-scopes-completion",
    "--completion-style=detailed",
    ros.get_compile_db_path(),
    },
```

so by simply adding a call to the function that simply returns nil if that package name is not found.
For now it works, with some work to be done in terms of handling the not found case and generalising the path.

2022-05-22 13:22 UTC, DavidePatria commented
this is a rather simple implementation. I would like to discuss another implementation I have in mind. I would be glad if you could help me deciding how to do it

2022-05-24 10:54 UTC, thibthib18 requested changes
Open to feedback there, but overall I think this function should reside more in your own config than in the plugin.

However, replacing the hardcoded "/home/davide/catkin_ws/build/" would require some function to check and find whether the file is within a catkin workspace (maybe is_inside_catkin_ws and/or get_catkin_ws_root?), which could be nice to have in the plugin.

What's good or not here depends more on one's workflow and use cases, which in my opinion is typically where one's custom config comes in.

2022-05-24 10:54 UTC, thibthib18 commented on lua/ros-nvim/package.lua
> +except: print('no_ros_on_system')"
Nice `except` logic to actually get errors from this python line.

Could put this `no_ros_on_system` in a variable and check if `pkg_name` matches this value? This way we can improve this function to make it return `ok, pkg_name` to make the success status clear to the user.

2022-05-24 10:54 UTC, thibthib18 commented on lua/ros-nvim/package.lua
> +except: print('no_ros_on_system')"
Something like 

```lua
if pkg_name == NOT_A_ROS_PACKAGE then
   return false, nil
end
...
return true, pkg_name
```
We'll need to update the users as well.

2022-05-24 10:54 UTC, thibthib18 commented on lua/ros-nvim/init.lua
> +-- local in_ros = false
please remove unused/debug code

2022-05-24 10:54 UTC, thibthib18 commented on lua/ros-nvim/init.lua
> +local not_package = "not in a ROS package"
If those are only used in `get_clangd_arg`, better move them inside.

2022-05-24 10:54 UTC, thibthib18 commented on lua/ros-nvim/package.lua
> +    print(pkg_name)
please remove the debug print here

2022-05-24 10:54 UTC, thibthib18 commented on lua/ros-nvim/init.lua
> +  if name ~= nil or name ~= 'no_ros_on_system' then
In general, it is more readable to revert if/else blocks this way to avoid nesting them: 

```lua
if not (name ~= nil or name ~= 'no_ros_on_system') then
      vim.notify(not_package, "warn")
      return
end
local db_path = "/home/davide/catkin_ws/build/" .. name
....
```

2022-05-24 10:54 UTC, thibthib18 commented on lua/ros-nvim/init.lua
> +    local db_path = "/home/davide/catkin_ws/build/" .. name
This will probably work only for you.

2022-05-24 10:54 UTC, thibthib18 commented on lua/ros-nvim/init.lua
> +    local db_file = "/home/davide/catkin_ws/build/" .. name .. "/compile_commands.json"
Not blocking: This assumes the user want to get the package-wise compile commands, and not directly the full compile commands at `catkin_ws/build/compile_commands.json`.

2022-05-24 10:54 UTC, thibthib18 commented on lua/ros-nvim/init.lua
> +function M.file_exists(name)
Would probably have this moved to some utils file.

2022-05-24 11:00 UTC, DavidePatria commented on lua/ros-nvim/init.lua
> +    local db_file = "/home/davide/catkin_ws/build/" .. name .. "/compile_commands.json"
I didn't know about the full `compile_commands.json` ! the setup function might include a variable to get full or package specific databases.

2022-05-24 11:04 UTC, DavidePatria commented on lua/ros-nvim/package.lua
> +except: print('no_ros_on_system')"
here there's a problem with multiline python commands from command line and concatenating `path` taken from vim. I couldn't find a way to make the try except work as a single line statement, which would be so much more useful in this case. `pwd` doesn't work and I don't know if the approach is right as python might not get the right path.

2022-05-24 11:10 UTC, DavidePatria commented
I was experimenting with notifications and making everything a bit more robust, let me get back with another larger (and cleaner) pull request, I might have done this in too much of an hurry, thanks for the feedbacks

2022-05-24 11:10 UTC, closed without merging